### ISSUE TITLE
Fix cull_idle_servers.py timestamp issue

### ISSUE THREAD

**Issue by slejdops** [malariagen/datalab#65]
[I 2019-05-20 10:56:48.798 JupyterHub log:158] 200 GET /hub/api/users (cull-idle@127.0.0.1) 69.47ms
Traceback (most recent call last):
  File "/usr/local/bin/cull_idle_servers.py", line 114, in <module>
    loop.run_sync(cull)
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/usr/local/bin/cull_idle_servers.py", line 87, in cull_idle
    if last_activity < cull_limit:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by slejdops** [comment]
Fixed, a newer version of the cull_idle_servers.py works.
https://github.com/jupyterhub/jupyterhub/blob/6b1046697/examples/cull-idle/cull_idle_servers.py
